#!/bin/sh

cd $(dirname "$0")

# pkcs1 private key
openssl genrsa -out private_pkcs1.pem 4096
# pkcs1 public key
openssl rsa -in private_pkcs1.pem -pubout -out public_pkcs1.pem

# pkcs8 private key
openssl pkcs8 -topk8 -inform PEM -in private_pkcs1.pem -outform pem -nocrypt -out private_pkcs8.pem
# pkcs8 public key
openssl rsa -in private_pkcs8.pem -pubout -out public_pkcs8.pem
